version: '3'
services:
    database:
        image: postgis/postgis:13-master
        # Required when running on platform other than amd64, like Apple M1/M2:
        # platform: linux/amd64
        volumes:
            - ./data/database:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: 'directus'
            POSTGRES_PASSWORD: 'directus'
            POSTGRES_DB: 'directus'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U directus']
            interval: 30s
            timeout: 10s
            retries: 5
    cache:
        image: redis:6
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            interval: 5s
            timeout: 20s
            retries: 10
    directus:
        build:
            context: .
            dockerfile: Dockerfile
        image: directus/directus:10.13.1
        ports:
            - 8055:8055
        volumes:
            - ./my_uploads:/directus/uploads
            - ./my_extensions:/directus/extensions
        depends_on:
            - cache
            - database
        environment:
            KEY: '255d861b-5996-5ea1-9aa3-922530ec40b1'
            SECRET: '6116487b-b5b5-52c2-cda1-c8022c45e263'

            DB_CLIENT: 'pg'
            DB_HOST: 'database'
            DB_PORT: '5432'
            DB_DATABASE: 'directus'
            DB_USER: 'directus'
            DB_PASSWORD: 'directus'

            CACHE_ENABLED: 'true'
            CACHE_STORE: 'redis'
            REDIS: 'redis://cache:6379'

            ADMIN_EMAIL: 'admin@example.com'
            ADMIN_PASSWORD: 'd1r3ctu5'

            # Make sure to set this in production
            # (see https://docs.directus.io/self-hosted/config-options#general)
            PUBLIC_URL: 'https://lyner.kommando.info'
       healthcheck:
            test:
                - CMD
                - wget
                - '-q'
                - '--spider'
                - 'http://127.0.0.1:8055/server/health'
            interval: 60s
            timeout: 10s
            retries: 5
        # Environment variables can also be defined in a file (for example `.env`):
        # env_file:
        #	  - .env
volumes:
    my_uploads:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./data/uploads
    my_extensions:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./data/extensions
